// Generated by CoffeeScript 1.8.0
(function() {
  if (location.hostname === "45678.github.io" && location.protocol !== "https:") {
    window.location = location.toString().replace("http:", "https:");
  }

}).call(this);
