// Generated by CoffeeScript 1.8.0
(function() {
  var renderID;

  if (location.hostname === "45678.github.io" && location.protocol !== "https:") {
    window.location = location.toString().replace("http:", "https:");
  }

  $(document).ready(function(event) {
    var pre, _i, _len, _ref, _results;
    _ref = document.querySelectorAll("pre");
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      pre = _ref[_i];
      _results.push(hljs.highlightBlock(pre));
    }
    return _results;
  });

  $(document).ready(function(event) {
    if (location.hash) {
      return renderID(location.hash.replace("#", ""));
    }
  });

  $(document).on("click", "a[href^='#']", function(event) {
    return renderID(event.currentTarget.href.toString().split("#")[1]);
  });

  renderID = function(id) {
    var el;
    el = document.getElementById(id);
    $("*.selected").removeClass("selected");
    $("a[href='#" + id + "']").addClass("selected");
    return $(el).next("h1, h2").addClass("selected");
  };

}).call(this);
