// Generated by CoffeeScript 1.10.0
(function() {
  var BLAKE2s, OriginalBLAKE2s,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  OriginalBLAKE2s = require("blake2s-js");

  module.exports = BLAKE2s = (function(superClass) {
    extend(BLAKE2s, superClass);

    function BLAKE2s(params) {
      OriginalBLAKE2s.call(this, params.length);
    }

    BLAKE2s.prototype.update = function(input) {
      OriginalBLAKE2s.prototype.update.call(this, input);
      return this;
    };

    return BLAKE2s;

  })(OriginalBLAKE2s);

}).call(this);
