// Generated by CoffeeScript 1.7.1
(function() {
  var BLAKE2, BLAKE2s,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BLAKE2s = require("BLAKE2s");

  module.exports = BLAKE2 = (function(_super) {
    __extends(BLAKE2, _super);

    function BLAKE2(params) {
      BLAKE2s.call(this, params.length);
    }

    BLAKE2.prototype.update = function(input) {
      BLAKE2s.prototype.update.call(this, input);
      return this;
    };

    return BLAKE2;

  })(BLAKE2s);

}).call(this);
