// Generated by CoffeeScript 1.7.1
(function() {
  var BLAKE2s, OriginalBLAKE2s,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  OriginalBLAKE2s = require("BLAKE2s");

  module.exports = BLAKE2s = (function(_super) {
    __extends(BLAKE2s, _super);

    function BLAKE2s(params) {
      OriginalBLAKE2s.call(this, params.length);
    }

    BLAKE2s.prototype.update = function(input) {
      OriginalBLAKE2s.prototype.update.call(this, input);
      return this;
    };

    return BLAKE2s;

  })(OriginalBLAKE2s);

}).call(this);
