// Generated by CoffeeScript 1.7.1
(function() {
  var BLAKE2, BLAKE2s;

  BLAKE2s = require("./BLAKE2s");

  module.exports = BLAKE2 = (function() {
    function BLAKE2(params) {
      this.delegate = new BLAKE2s(params.length);
    }

    BLAKE2.prototype.update = function(input) {
      this.delegate.update(input);
      return this;
    };

    BLAKE2.prototype.digest = function() {
      return this.delegate.digest();
    };

    return BLAKE2;

  })();

}).call(this);
