// Generated by CoffeeScript 1.8.0
(function() {
  var Blob;

  module.exports = Blob = (function() {
    function Blob(input, options) {
      var part, _i, _len;
      if (options == null) {
        options = {};
      }
      switch (input != null ? input.constructor : void 0) {
        case void 0:
          this.buffer = new Buffer(0);
          break;
        case Buffer:
          this.buffer = input;
          break;
        case Number:
          this.buffer = new Buffer(input);
          break;
        case Array:
          this.buffer = new Buffer(0);
          for (_i = 0, _len = input.length; _i < _len; _i++) {
            part = input[_i];
            this.buffer = Buffer.concat([this.buffer, new Buffer(part)]);
          }
      }
      this.type = options.type;
      this.size = this.buffer.length;
    }

    Blob.prototype.slice = function(start, end) {
      return new Blob(this.buffer.slice(start, end));
    };

    return Blob;

  })();

}).call(this);
