// Generated by CoffeeScript 1.10.0
(function() {
  var BLAKE2s, Base58;

  Base58 = require("base-58");

  BLAKE2s = require("./BLAKE2s");

  exports.encode = function(publicKey) {
    var i, index, slots;
    if ((publicKey != null ? publicKey.length : void 0) === 32) {
      slots = new Uint8Array(33);
      for (index = i = 0; i <= 32; index = ++i) {
        slots[index] = publicKey[index];
      }
      slots[32] = (new BLAKE2s({
        length: 1
      })).update(publicKey).digest()[0];
      return Base58.encode(slots);
    } else {
      return void 0;
    }
  };

  exports.decode = function(miniLockID) {
    var encodedChecksum, publicKey, slots, trueChecksum;
    slots = Base58.decode(miniLockID);
    if (slots.length === 33) {
      publicKey = new Uint8Array(slots.subarray(0, 32));
      encodedChecksum = slots[32];
      trueChecksum = (new BLAKE2s({
        length: 1
      })).update(publicKey).digest()[0];
      if (encodedChecksum === trueChecksum) {
        return publicKey;
      }
    }
    return void 0;
  };

  exports.isAcceptable = function(miniLockID) {
    return /^[1-9A-Za-z]{40,55}$/.test(miniLockID) && (this.decode(miniLockID) != null);
  };

}).call(this);
