// Generated by CoffeeScript 1.8.0
(function() {
  var miniLockLib;

  miniLockLib = module.exports;

  miniLockLib.makeKeyPair = function(secretPhrase, emailAddress, callback) {
    var operation;
    operation = new miniLockLib.KeyPairOperation({
      secretPhrase: secretPhrase,
      emailAddress: emailAddress
    });
    return operation.start(callback);
  };

  miniLockLib.encrypt = function(params, callback) {
    var operation;
    operation = new miniLockLib.EncryptOperation(params);
    return operation.start(callback);
  };

  miniLockLib.decrypt = function(params, callback) {
    var operation;
    operation = new miniLockLib.DecryptOperation(params);
    return operation.start(callback);
  };

  miniLockLib.SecretPhrase = require("./SecretPhrase");

  miniLockLib.EmailAddress = require("./EmailAddress");

  miniLockLib.ID = require("./ID");

  miniLockLib.KeyPairOperation = require("./KeyPairOperation");

  miniLockLib.EncryptOperation = require("./EncryptOperation");

  miniLockLib.DecryptOperation = require("./DecryptOperation");

  miniLockLib.Base58 = require("base-58");

  miniLockLib.BLAKE2s = require("./BLAKE2s");

  miniLockLib.Entropizer = require("entropizer");

  miniLockLib.NaCl = require("tweetnacl");

  miniLockLib.NaCl.stream = require("nacl-stream").stream;

  miniLockLib.scrypt = require("./scrypt-async");

}).call(this);
