// Generated by CoffeeScript 1.7.1
(function() {
  var NaCl, stream;

  stream = require("nacl-stream").stream;

  NaCl = require("tweetnacl");

  NaCl.stream = stream;

  module.exports = NaCl;

}).call(this);
