// Generated by CoffeeScript 1.7.1
(function() {
  var NACL, stream;

  stream = require("nacl-stream").stream;

  NACL = require("tweetnacl");

  NACL.stream = stream;

  module.exports = NACL;

}).call(this);
