// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(start, end, callback) {
    if (this.fileReader == null) {
      this.fileReader = new FileReader;
    }
    this.fileReader.readAsArrayBuffer(this.data.slice(start, end));
    this.fileReader.onabort = function(event) {
      console.error("@fileReader.onabort", event);
      return callback("File read abort.");
    };
    this.fileReader.onerror = function(event) {
      console.error("@fileReader.onerror", event);
      return callback("File read error.");
    };
    return this.fileReader.onload = function(event) {
      var sliceOfBytes;
      sliceOfBytes = new Uint8Array(event.target.result);
      return callback(void 0, sliceOfBytes);
    };
  };

}).call(this);
