// Generated by CoffeeScript 1.10.0
(function() {
  var Entropizer, entropizer;

  exports.isAcceptable = function(secretPhrase) {
    return (secretPhrase != null ? secretPhrase.length : void 0) >= 32 && entropizer.evaluate(secretPhrase) >= 200;
  };

  Entropizer = require("entropizer");

  entropizer = new Entropizer;

}).call(this);
