// Generated by CoffeeScript 1.10.0
(function() {
  exports.numberToByteArray = function(n) {
    var byteArray, i, index;
    byteArray = new Uint8Array(4);
    for (index = i = 0; i <= 4; index = ++i) {
      byteArray[index] = n & 255;
      n = n >> 8;
    }
    return byteArray;
  };

  exports.byteArrayToNumber = function(byteArray) {
    var i, index, n;
    n = 0;
    for (index = i = 3; i >= 0; index = --i) {
      n += byteArray[index];
      if (index !== 0) {
        n = n << 8;
      }
    }
    return n;
  };

}).call(this);
