// Generated by CoffeeScript 1.7.1
(function() {
  exports.numberToByteArray = function(n) {
    var byteArray, index, _i;
    byteArray = new Uint8Array(4);
    for (index = _i = 0; _i <= 4; index = ++_i) {
      byteArray[index] = n & 255;
      n = n >> 8;
    }
    return byteArray;
  };

  exports.byteArrayToNumber = function(byteArray) {
    var index, n, _i;
    n = 0;
    for (index = _i = 3; _i >= 0; index = --_i) {
      n += byteArray[index];
      if (index !== 0) {
        n = n << 8;
      }
    }
    return n;
  };

}).call(this);
