// Generated by CoffeeScript 1.10.0
(function() {
  var ref;

  if ((typeof root !== "undefined" && root !== null ? (ref = root.process) != null ? ref.argv : void 0 : void 0) != null) {
    exports.tape = require("tape");
    exports.miniLockLib = require("..");
  } else {
    exports.tape = require("./window_test_harness");
    exports.miniLockLib = window.miniLockLib;
  }

}).call(this);
